name: Trigger auto deployment for acatestharsha

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/acatestharsha-AutoDeployTrigger-facb7af6-579c-4370-8fd8-aaac9be72a31.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acrtestharsha123.azurecr.io
          username: ${{ secrets.ACATESTHARSHA_REGISTRY_USERNAME }}
          password: ${{ secrets.ACATESTHARSHA_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acrtestharsha123.azurecr.io/acatestharsha:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACATESTHARSHA_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n acatestharsha -g rg-dataservices --server acrtestharsha123.azurecr.io --username  ${{ secrets.ACATESTHARSHA_REGISTRY_USERNAME }} --password ${{ secrets.ACATESTHARSHA_REGISTRY_PASSWORD }}
            az containerapp update -n acatestharsha -g rg-dataservices --image acrtestharsha123.azurecr.io/acatestharsha:${{ github.sha }}
